name: JoshuaAllenGreen
favicon: null
layout_spectrum: 0.8
title: Photography by Josh Green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16191a'
    - '#d7d7d7'
    - '#a76f62'
    - '#f5a069'
    - '#49c3bc'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
