name: JoshuaAllenGreen
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.25694
title: Photography by Josh Green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e8da'
    - '#8f9dad'
    - '#28693e'
    - '#aa6a59'
    - '#483435'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
